version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/pull_app.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root